[package]
name = "zkyc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.101"
chrono = "0.4.43"
num-bigint = "0.4.6" # only used for tests
plonky2 = "1.1.0"
poseidon-hash = "0.1.3"
rand = "0.9.2"
